version: "3.4"
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1024
      - TZ=America/Denver
    volumes:
      - /opt/remotefs/shared_storage/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped
