version: "3.4"
services:
    jackett:
        hostname: jackett
        restart: unless-stopped
        ports:
        - 9118:9117
        container_name: jackett
        image: linuxserver/jackett:latest

        
        environment:
        - PUID=${PUID} # default user id, defined in .env
        - PGID=${PGID} # default group id, defined in .env
        - TZ=${TZ} # timezone, defined in .env
        volumes:
        - /etc/localtime:/etc/localtime:ro
        - ${MEDIA_SERVER}/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
        - ${MEDIA_SERVER}/config/jackett:/config
    sonarr:
        hostname: sonarr
        container_name: sonarr
        image: linuxserver/sonarr:latest
        restart: unless-stopped
        ports:
            - "8989:8989" 
        environment:
            - PUID=${PUID} # default user id, defined in .env
            - PGID=${PGID} # default group id, defined in .env
            - TZ=${TZ} # timezone, defined in .env
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${MEDIA_SERVER}/config/sonarr:/config # config files
            - ${MEDIA_SERVER}/complete/tv:/tv # tv shows folder
            - ${MEDIA_SERVER}/downloads:/downloads # download folder
    
    radarr:
        hostname: radarr
        container_name: radarr
        image: linuxserver/radarr:latest
        restart: unless-stopped
        ports:
            - "7878:7878"
        environment:
            - PUID=${PUID} # default user id, defined in .env
            - PGID=${PGID} # default group id, defined in .env
            - TZ=${TZ} # timezone, defined in .env
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ${MEDIA_SERVER}/config/radarr:/config # config files
            - ${MEDIA_SERVER}/complete/movies:/movies # movies folder
            - ${MEDIA_SERVER}/downloads:/downloads # download folder

