version: "3.4"
services:
    jackett:
        hostname: jackett
        restart: unless-stopped
        ports:
        - 9118:9117
        container_name: jackett
        image: linuxserver/jackett:latest

        
        environment:
        - PUID=1000 # default user id, defined in .env
        - PGID=1024 # default group id, defined in .env
        - TZ=America/Denver # timezone, defined in .env
        volumes:
        - /etc/localtime:/etc/localtime:ro
        - /opt/remotefs/media_server/downloads/torrent-blackhole:/downloads # place where to put .torrent files for manual download
        - /opt/remotefs/media_server/config/jackett:/config
    sonarr:
        hostname: sonarr
        container_name: sonarr
        image: linuxserver/sonarr:latest
        restart: unless-stopped
        ports:
            - "8989:8989" 
        environment:
            - PUID=1000 # default user id, defined in .env
            - PGID=1024 # default group id, defined in .env
            - TZ=America/Denver # timezone, defined in .env
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/remotefs/media_server/config/sonarr:/config # config files
            - /opt/remotefs/media_server/complete/tv:/tv # tv shows folder
            - /opt/remotefs/media_server/downloads:/downloads # download folder
    
    radarr:
        hostname: radarr
        container_name: radarr
        image: linuxserver/radarr:latest
        restart: unless-stopped
        ports:
            - "7878:7878"
        environment:
            - PUID=1000 # default user id, defined in .env
            - PGID=1024 # default group id, defined in .env
            - TZ=America/Denver # timezone, defined in .env
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /opt/remotefs/media_server/config/radarr:/config # config files
            - /opt/remotefs/media_server/complete/movies:/movies # movies folder
            - /opt/remotefs/media_server/downloads:/downloads # download folder
    main_app:
        hostname: app
        ports:
                - "9999:9999"
        container_name: app
        image:  plaggm/ddb-flask-app
        restart: unless-stopped
        #    main_nginx:
        #        container_name: tracker_nginx
        #        image: nginx
        #        environment:
        #            - PUID=${PUID:-1000}
        #            - PGID=${PGID:-1111}
        #            - TZ=America/Denver
        #        volumes:
        #            - ${TRACKER_NGINX_CONFIG}:/etc/nginx/nginx.conf:ro
        #        restart: unless-stopped
        #        ports:
        #            - "80:80"
        #        depends_on:
        #            - main_app
        #            - sonarr
        #            - radarr
        #            - jackett
