version: "3.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1024
      - TZ=US/Denver
    volumes:
      - /opt/remotefs/shared_storage/config/prowler/:/config
    ports:
      - 9696:9696
    restart: unless-stopped
