 
 version: "3.4"
 services:
   wireguard:
     image: linuxserver/wireguard
     container_name: wireguard
     cap_add:
       - NET_ADMIN
       - SYS_MODULE
     environment:
       - PUID=${PUID:-1000}
       - PGID=${PGID:-1111}
       - TZ=${TZ}
 #      - SERVERURL=wireguard.domain.com #optional
 #      - SERVERPORT=51820 #optional
 #      - PEERS=1 #optional
 #      - PEERDNS=auto #optional
 #      - INTERNAL_SUBNET=10.13.13.0 #optional
     volumes:
       - ${VPN_CONFIG}:/config
       - /lib/modules:/lib/modules
     ports:
       - 51820:51820/udp
     sysctls:
       - net.ipv4.conf.all.src_valid_mark=1
     restart: unless-stopped
 
   transmission:
     image: linuxserver/transmission
     container_name: transmission
     environment:
       - PUID=1000
       - PGID=1024
       - TZ=US/Mountain
 #      - TRANSMISSION_WEB_HOME=/combustion-release/ 
 #optional
 #      - USER=user #optional
 #      - PASS=password #optional
     volumes:
       - ${MEDIA_SERVER_ROOT}/config/trans:/config
       - ${MEDIA_SERVER_ROOT}/downloads:/downloads
       - ${MEDIA_SERVER_ROOT}/downloads/watch:/watch
     network_mode: service:wireguard
     restart: unless-stopped
   deluge:
    image: lscr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1024
      - TZ=US/Mountain
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ${MEDIA_SERVER_ROOT}/config/deluge:/config
      - ${MEDIA_SERVER_ROOT}/downloads/deluge:/downloads
    #ports:
        #- 8112:8112
        #- 6881:6881
        #- 6881:6881/udp
    restart: unless-stopped 
    network_mode: service:wireguard
   nginx:
     image: nginx
     container_name: nginx
     environment:
        - PUID=${PUID:-1000}
        - PGID=${PGID:-1111}
        - TZ=${TZ}
     volumes:
       - ${NGINX_CONFIG}:/etc/nginx/nginx.conf:ro
     ports:
       - 9091:9091
         #- 8112:8112
     restart: unless-stopped
   nginxde:
        
     image: nginx
     container_name: nginxde
     environment:
        - PUID=${PUID:-1000}
        - PGID=${PGID:-1111}
        - TZ=${TZ}
     volumes:
       - ${NGINX_CONFIG_DE}:/etc/nginx/nginx.conf:ro
     ports:
             - 8112:8112
         #- 8112:8112
     restart: unless-stopped

 
