services:
  mylar3:
    image: lscr.io/linuxserver/mylar3
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1024
    volumes:
      - /opt/remotefs/media_server/config:/config
      - /opt/remotefs/media_server/complete/comics:/comics
      - /opt/remotefs/media_server/downloads:/downloads
    ports:
      - 8090:8090
    restart: unless-stopped
