version: "3"

services:
  jellyfin:
          #    image: linuxserver/jellyfin:nightly
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    environment:
      PUID: 1000
      PGID: 1024
      TZ: America/Denver
      UMASK_SET: "022"
    volumes:
      - /home/mplagge/jellyfin:/config
      - /opt/remotefs/media_server/complete:/media
      - /opt/remotefs/media_server/complete/tv:/tv
      - /opt/remotefs/media_server/complete/movies:/movies
      - /dev/shm:/config/data/transcoding-temp/transcodes
      - /opt/vc/lib:/opt/vc/lib   ## OpenMax Libraries
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/card1:/dev/dri/card1
      - /dev/video10:/dev/video10
      - /dev/video11:/dev/video10
      - /dev/video12:/dev/video10
      - /dev/vchiq:/dev/vchiq
    restart: always
